name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - runs: echo"This job was automatically triggered by a ${{ github.event_name }} event."
      - runs: pwd
      - runs: ls -la
